name: wolfdeveloper_ui_kit
description: "design system dos applicatives da wolfdeveloper"
version: 0.0.1
homepage: https://www.wolfdeveloper.com.br

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0